import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/main.module.css'
import TextField from '@mui/material/TextField';
import * as React from 'react';
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';
import ButtonGroup from '@mui/material/ButtonGroup';
import Box from '@mui/material/Box';
import { border } from '@mui/system';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>TourSerVit</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>

                <div className={styles.background}></div>
                <div className={styles.image}></div>

                <div className={styles.wrap}>
                    <div className={styles.logo}></div>

                        <TextField className={styles.email}
                            label="이메일"
                            id="standard-size-small"
                            defaultValue=" "
                            size="small"
                            variant="standard"
                        />

                        <TextField className={styles.password}
                            label="비밀번호"
                            id="standard-size-small"
                            defaultValue=" "
                            size="small"
                            variant="standard"
                        />

                    <Button className={styles.login} variant="contained">로그인</Button>

                    <div className={styles.other}>
                        <span>또는</span>
                    </div>

                    <div className={styles.social}>
                        <span>google</span>
                        <span>facebook</span>
                        <span>naver</span>
                    </div>

                    <ButtonGroup className={styles.find} variant="text" aria-label="text button group" sx={{
                                "& .MuiButtonGroup-grouped:not(:last-of-type)": {
                                    borderColor : "#b9b9b9"
                                }
                            }}>
                        <Button>아이디 찾기</Button>
                        <Button>비밀번호 찾기</Button>
                        <Button>회원가입</Button>
                    </ButtonGroup>
                </div>

            </main>
        </>
    )
}
