import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/membership.module.css'
import TextField from '@mui/material/TextField';
import * as React from 'react';
import Button from '@mui/material/Button';
import { useRouter } from 'next/router';
import IconButton from '@mui/material/IconButton';
import Visibility from '@mui/icons-material/Visibility';
import VisibilityOff from '@mui/icons-material/VisibilityOff';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const router = useRouter();

    const link = () => {
        router.push("/")
    }
    const [showPassword, setShowPassword] = React.useState(false);

    const handleClickShowPassword = () => setShowPassword((show) => !show);

    const handleMouseDownPassword = (event: React.MouseEvent<HTMLButtonElement>) => {
        event.preventDefault();
    };
    return (
        <>
            <Head>
                <title>TourSerVit</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>

                <div className={styles.background}></div>
                <div className={styles.image}></div>

                <div className={styles.wrap}>
                    <Image src="/logo.png" alt="TourServiT" className={styles.logo} width={400} height={72}></Image>

                    <TextField className={styles.email}
                        label="이메일"
                        id="standard-size-small"
                        defaultValue=""
                        size="small"
                        variant="standard"
                        // sx={{
                        //     "&.Mui-focused": {
                        //         color: "#b9b9b9"
                        //     }

                        // }}
                    />

                    <div className={styles.icon}>
                        <TextField className={styles.password}
                            label="비밀번호"
                            id="standard-size-small"
                            defaultValue=""
                            size="small"
                            variant="standard"
                            type={showPassword ? 'text' : 'password'}

                        />
                        <IconButton
                            aria-label="toggle password visibility"
                            onClick={handleClickShowPassword}
                            onMouseDown={handleMouseDownPassword}
                        >
                            {showPassword ? <VisibilityOff /> : <Visibility />}
                        </IconButton>
                    </div>

                    <div className={styles.icon1}>
                        <TextField className={styles.confirmpassword}
                            label="비밀번호 확인"
                            id="standard-size-small"
                            defaultValue=""
                            size="small"
                            variant="standard"
                            type={showPassword ? 'text' : 'password'}

                        />
                        <IconButton
                            aria-label="toggle password visibility"
                            onClick={handleClickShowPassword}
                            onMouseDown={handleMouseDownPassword}
                        >
                            {showPassword ? <VisibilityOff /> : <Visibility />}
                        </IconButton>
                    </div>
                    <Button className={styles.membership} variant="contained">가입하기</Button>

                    <div className={styles.other}>
                            <span>이미 회원이신가요?</span>
                            <span onClick={link}>로그인 하기</span>
                    </div>

                </div>
            </main>
        </>
    )
}
